- RLBotPack/Sniper/rendering.py
- RLBotPack/Sniper/rldata.py
- RLBotPack/Sniper/rlmath.py
- RLBotPack/Sniper/sniper.cfg
- RLBotPack/Sniper/sniper.py
- RLBotPack/Sniper/vec.py
Changes:
- Way cleaner code
- Does not break replays
- Does not use RLU anymore
- ~~Spike Rush support~~ nope, my initial idea didn't work
> Updated Sniper to v1.2

- RLBotPack/Kamael/Kamael.py
- RLBotPack/Kamael/States.py
- RLBotPack/Kamael/Utilities.py
- RLBotPack/Kamael/appearance.cfg
Just bringing botpack version up to current. Also removed numba imports since it was causing additional friction and isn't being used currently anyway.
> Kamael Update - Improved wall movement, shot placement and team code.

- RLBotPack/Diablo/States.py
- RLBotPack/Diablo/Utilities.py
- RLBotPack/Diablo/appearance.cfg
- RLBotPack/Diablo/diablo.py
actually retains it's aerial target between frames now, omg! ;p
> Updating Diablo to current

- RLBotPack/Codename_Cryo/Codename_Cryo.py
- RLBotPack/Codename_Cryo/GoslingUtils/objects.py
- RLBotPack/Codename_Cryo/GoslingUtils/routines.py
- RLBotPack/Codename_Cryo/GoslingUtils/tools.py
- RLBotPack/Codename_Cryo/GoslingUtils/utils.py
FormularSumo found out it was still broken, so fixing the fix
> update to fix broken bot

- RLBotPack/blind_and_deaf/bot.py
- RLBotPack/blind_and_deaf/hover.py
- RLBotPack/blind_and_deaf/kickoff.py
People were reporting that blind and deaf didn't jump into the air sometimes so this should make it more reliable. I also added a basic ATBA kickoff just so you don't have to touch the ball first to get things started.
> Added "kickoffs" and fixed jumping into the air

- RLBotPack/TwitchInteraction/BallBotherer/ball_botherer.cfg
- RLBotPack/TwitchInteraction/BallBotherer/ball_botherer.py
- RLBotPack/TwitchInteraction/BallBotherer/requirements.txt
- RLBotPack/TwitchInteraction/BallBotherer/util/vec.py
- RLBotPack/TwitchInteraction/CarBotherer/car_botherer.cfg
- RLBotPack/TwitchInteraction/CarBotherer/car_botherer.py
- RLBotPack/TwitchInteraction/CarBotherer/requirements.txt
- RLBotPack/TwitchInteraction/CarBotherer/util/orientation.py
- RLBotPack/TwitchInteraction/CarBotherer/util/vec.py
- RLBotPack/TwitchInteraction/TwitchBroker/overlay/twitch_broker_overlay.css
- RLBotPack/TwitchInteraction/TwitchBroker/overlay/twitch_broker_overlay.html
- RLBotPack/TwitchInteraction/TwitchBroker/requirements.txt
- RLBotPack/TwitchInteraction/TwitchBroker/twitch_broker.cfg
- RLBotPack/TwitchInteraction/TwitchBroker/twitch_broker_script.py
- RLBotPack/TwitchInteraction/TwitchBroker/twitchbroker/action_and_server_id.py
- RLBotPack/TwitchInteraction/TwitchBroker/twitchbroker/overlay_data.py
- RLBotPack/TwitchInteraction/TwitchBroker/twitchbroker/twitch_broker.py
https://www.twitch.tv/tarehart/clip/FaithfulPatientDillCopyThis
> Adding RLBotTwitchBroker, along with Ball Botherer and Car Botherer.

- RLBotPack/recommendations.json
Related to: https://github.com/RLBot/RLBotGUI/pull/105
> Recommendations

- RLBotPack/Snek/appearance.cfg
- RLBotPack/Snek/requirements.txt
- RLBotPack/Snek/snek.cfg
- RLBotPack/Snek/snek.py
> Updated Snek: removed RLU dependency, added vertical turns, and clean up

- RLBotPack/Snek/util/info.py
- RLBotPack/Snek/util/predict.py
- RLBotPack/Snek/util/rendering.py
- RLBotPack/Snek/util/rlmath.py
- RLBotPack/Snek/util/vec.py
I created the commit with @NicEastvillage as the author since I am just copying over the missed code. 
The missing code is from here: https://github.com/NicEastvillage/RLBot-Snek/tree/master/snek/util
> Add missing util directory for Snek

- RLBotPack/Kamael/Kamael.py
- RLBotPack/Kamael/beard_states.py
- RLBotPack/Kamael/beard_utilities.py
Fixed a bug causing erratic targeting and general spaz behavior in duels, got dribble carries slightly working again and tweaked some parameters.
> Updating Kamael

- RLBotPack/TwitchInteraction/TwitchBroker/.gitignore
- RLBotPack/TwitchInteraction/TwitchBroker/overlay/twitch_broker_overlay.css
- RLBotPack/TwitchInteraction/TwitchBroker/overlay/twitch_broker_overlay.html
- RLBotPack/TwitchInteraction/TwitchBroker/twitch_broker_script.py
- RLBotPack/TwitchInteraction/TwitchBroker/twitchbroker/overlay_data.py
- RLBotPack/TwitchInteraction/TwitchBroker/twitchbroker/twitch_broker.py
Overlay looks nicer too. This is identical to the latest commit in https://github.com/RLBot/RLBotTwitchBroker (https://github.com/RLBot/RLBotTwitchBroker/commit/3ae3d1efdaf491a94a329bc1537bc78e0dc32b75)
> Better vote meters for twitch broker.

- RLBotPack/VirxEB/Bot.cfg
- RLBotPack/VirxEB/VirxEB.cfg
- RLBotPack/VirxEB/VirxEB.py
- RLBotPack/VirxEB/prediction.py
- RLBotPack/VirxEB/util/agent.py
- RLBotPack/VirxEB/util/routines.py
- RLBotPack/VirxEB/util/tools.py
- RLBotPack/VirxEB/util/utils.py
There are some changes in here for Moonbots, but I'm not going to remove them just for this PR. (Also y would I?)
Unlimited boost is now understood
Adjustments for low gravity situations
New enemy time to ball prediction (runs @ 5hz)
The bot drives at 2300uus until it's within 1280uus of the ball (when shooting)
Car turning/driving simulation (runs @ 30hz and is a change to VirxERLU-CLib)
Less overcommits when shadowing
Fixed pathfinding when inside the net
Fixed finding aerials via find_shot and find_any_shot
Much better 1's play
Fix sending 2 bots on the back left & back right kickoffs
> Update to COMM-77 (bug fixes & better 1's play)

- RLBotPack/Kamael/beard_states.py
I had forgotten that the kickoffs in the previous update were untested. Sadly they are not up to snuff, not by a long shot. This should be my last update for a while. Sorry for the hassle.
> Reverted Kamael's kickoffs to an earlier version

- RLBotPack/TensorBot/src/appearance.cfg
- RLBotPack/TensorBot/src/bot.py
Ok, I think I have successfully rebased the fork and its only showing this commit
> pulled rlbot changes, now updating tensorbot

- RLBotPack/TensorBot/src/bot.py
I forgot to initialize and variable and it didn't like that.
> Added member variable initialization

- RLBotPack/VirxEB/VirxEB.py
- RLBotPack/VirxEB/util/routines.py
Errors are no longer thrown when VirxEB has teammates
Only 1 bot goes for kickoff
I hate 3's
Playstyle selection is more like 1's in 2's & 3's
Few defensive changes
> Fix errors in VirxEB

- RLBotPack/Bribblebot/bot.py
- RLBotPack/Bribblebot/stateMachine.py
Small update to bribblebot to maintain status as goto bot for TPS debugging ;)
> fix printing lag on kickoffs with new rlbot socket version

- RLBotPack/blind_and_deaf/_story_mode_bot.cfg
- RLBotPack/blind_and_deaf/bot.cfg
- RLBotPack/blind_and_deaf/bot.py
- RLBotPack/blind_and_deaf/get_to_air_point.py
- RLBotPack/blind_and_deaf/hover.py
- RLBotPack/blind_and_deaf/kickoff.py
Improved kickoff, fixed most of the cases where it isn't able to stabilize inside the goal.
There are intentionally two config files, one of them starts with `_` so it will not appear in the GUI when https://github.com/RLBot/RLBotGUI/pull/136 is deployed.
That version is intended for story mode, it has an intentional flaw to make the mission easier (lets slip by ground-level shots under it)
> Improve blind and deaf, add story mode version

- RLBotPack/Kamael/Kamael.py
Just a small fix, but that also made it worth it @Impossibum
> Fix Kam launch on Linux

- RLBotPack/50-50-MiniGame/fiftyfiftyminigame.py
- Fixed pause from game pause to state-setter hold players in place. This resulted in more consistent kickoffs
- Fixed tick counter to use the more robust ingame time for pause
> Fixed restart-pause in 50/50 MiniGame v2 (thanks Darxeal)

- RLBotPack/Omus/bot.cfg
- RLBotPack/Omus/requirements.txt
> Omus Hotfix (again, sorry!)

- RLBotPack/SignificanceBar/SignificanceBar.cfg
- RLBotPack/SignificanceBar/sigbar.py
Add significance bar script since the rlgym crew loves significance
> Add significance bar script

- RLBotPack/HP OMEN/utils.py
Created a new repo, I think that was what you were asking darx...
> Adding omen to botpack

- RLBotPack/Kamael_family/Aries.cfg
Not a biggy, I simply forgot to add the path to their logo.
> adding aries logo

- RLBotPack/DisasterBot/disaster_bot.cfg
tags for the gui need to be in the details section
> Fix tags on DisasterBot

- RLBotPack/Seer/requirements.txt
Seer's requirements.txt are to include "sklearn"
> Update Seer's requirements.txt

- RLBotPack/SuperchargedBots/SuperchargedBots.cfg
& all the other bots will prob be better, too
> Tuning SuperchargedBots for Nexto

- RLBotPack/quantum-league/config.cfg
- RLBotPack/quantum-league/src/main.py
- RLBotPack/quantum-league/src/quantum_league.py
A new 1-player minigame, powered by a script. I'll announce and explain it in #events after this gets merged
> Quantum League

- RLBotPack/quantum-league/config.cfg
- RLBotPack/quantum-league/requirements.txt
- RLBotPack/quantum-league/src/main.py
- RLBotPack/quantum-league/src/quantum_league.py
- reset button
- practice mode (failing or restarting only resets the last timeline)
- now preserves your selected map
> Quantum League update

- RLBotPack/Oneborg/src/bot.py
There was a bug that prevented Oneborg from moving in Dropshot, which with this PR will be fixed.
> Fixing Oneborg For Dropshot

- RLBotPack/Engine/Engine/requirements.txt
- RLBotPack/Monkey/requirements.txt
- RLBotPack/Omus/requirements.txt
- fix typo
- add missing requirements
> Minor fixes to requirements.txt

- RLBotPack/SSL_of_GS/src/bot.cfg
To clarify that state setting is required.
> Slight change in SSL of GS's description

- RLBotPack/Kamael_family/requirements.txt
> Update Kamael requirements.txt

- RLBotPack/Noob_Black/src/bot.cfg
I found that changing this one line fixed an issue I found where the bot wouldn't appear in the ui menu.
> Fix Noob Black not appearing in the ui.

- RLBotPack/Engine/Engine/requirements.txt
- RLBotPack/Monkey/requirements.txt
Tested it with a new user <https://discord.com/channels/348658686962696195/1332752709723492392>
> Make Monkey and Engine work without git
